version: '2'

services:
    mysql:
        build: ./mysql
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: blog
           MYSQL_USER: blog
           MYSQL_PASSWORD: blog
        volumes:
           - "./mysql/my.cnf:/etc/mysql/my.cnf"
           - "./mysql/data:/var/lib/mysql"
        ports: 
           - "3306:3306"
    phpfpm:
        build: ./php
        ports:
           - "9090:9090"
        links:
           - mysql
        depends_on:
           - mysql
        volumes:
           - "/develop/docker/dockerDevelop/socket:/var/www/html"
           - "./php/www.conf:/usr/local/etc/php-fpm/www.conf"
    nginx:
        image: nginx:1.14-alpine
        ports:
           - "80:80"
           - "443:443"
        links:
           - "phpfpm"
        depends_on:
           - phpfpm
        volumes:
           - "/develop/docker/dockerDevelop/socket:/var/www/html"
           - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
           - "./nginx/conf.d:/etc/nginx/conf.d"